#!/bin/bash

curr_dir=$(pwd)
AUR_PACKAGES=(
    'zsh-theme-powerlevel9k'
    'nerd-fonts-source-code-pro'
    'oh-my-zsh-git'
  )

function installOhMyZsh() {
  sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
  git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  git clone https://github.com/zsh-users/zsh-history-substring-search ~/.oh-my-zsh/custom/plugins/zsh-history-substring-search
  git clone https://github.com/zsh-users/zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  git clone https://github.com/zsh-users/zsh-completions ~/.oh-my-zsh/custom/plugins/zsh-completions
  cd ~/.oh-my-zsh/custom/themes/powerlevel9k
  git checkout next
}

# install packages

function install_pac {
  i=0
  input=$(whiptail --passwordbox "Enter password" 10 30 3>&1 1>&2 2>&3)

  for pac in base-devel pulseaudio pulseaudio-alsa xorg xorg-server xorg-xinit xdg-utils xorg-xprop xorg-xset xorg-xbacklight i3-wm i3-resurrect dmenu rofi sudo i3blocks alacritty lxappearance firefox noto-fonts-emoji flameshot acpi wget bc i3lock imagemagick picom ranger sxiv xwallpaper gvim mpv mpd mpc playerctl fzf unzip unrar xclip tmux zsh
  do
   echo $input | sudo -S pacman --noconfirm --needed -S $pac > /dev/null 2>&1
   echo XXX
   i=$((i + 2.7027027027))
   echo $i
   echo "Installing... $pac"
   echo XXX
  done | whiptail --gauge "Installing..." 6 50 0

  clear
  echo "Successfully Installed default packages!"
}

function reconfig_files {
  #remove config files
  rm -fr ~/.bg-wallpapers
  rm -fr ~/.config
  rm -fr ~/.local
  rm -fr ~/.vim
  rm -fr ~/.themes
  rm -f ~/.bash_profile
  rm -f ~/.bashrc
  rm -f ~/.vimrc
  rm -f ~/.xinitrc
  rm -f ~/.tmux.conf
  rm -f ~/.zprofile
  rm -f ~/.zshenv
  rm -f ~/.zshrc

  #copy all configs
  cp -fr $curr_dir/.bg-wallpapers ~/.bg-wallpapers
  cp -frs $curr_dir/.config ~/.config
  cp -frs $curr_dir/.local ~/.local
  cp -frs $curr_dir/.vim ~/.vim
  cp -frs $curr_dir/.themes ~/.themes
  cp -fs $curr_dir/.bash_profile ~/.bash_profile
  cp -fs $curr_dir/.bashrc ~/.bashrc
  cp -fs $curr_dir/.vimrc ~/.vimrc
  cp -fs $curr_dir/.xinitrc ~/.xinitrc
  cp -fs $curr_dir/.zprofile ~/.zprofile
  cp -fs $curr_dir/.zshenv ~/.zshenv
  cp -fs $curr_dir/.zshrc ~/.zshrc

  mkdir ~/.local/share

  echo "Reconfigure success!"
}

whiptail --title "What to do?" --checklist --separate-output "Please select" 10 65 3 "INSTALL_PACKAGES" "It will install default packages" ON "RECONFIGURE_FILES" "Set the default configs" OFF 2>results

while read choice
do
  case $choice in
    INSTALL_PACKAGES) install_pac
    ;;
    RECONFIGURE_FILES) reconfig_files
    ;;
    *)
    ;;
  esac
done < results

rm $curr_dir/results
